### ISSUE TITLE
todo: evaluate using a simple tunnel instead of the CONNECT method for http

### ISSUE THREAD

**Issue by nlf** [npm/agent#23]
currently both http and https proxies use the http CONNECT method. for `https` this method must be supported, but for `http` it's not a requirement and proxies may be implemented without this support. we should do some research and see if it's better for us to switch to a simple tunnel for http.

**Comment by aSapien** [comment]
Hey @nlf, I've scoured the internet to find this! 

I know it's been 3 years but maybe you know how to point me in the right direction.
I have a corporate http-only proxy in front of an NPM registry, but it seems that any `npmrc` proxy configuration I try ends up with the `CONNECT` request to the http-proxy. 

Can you please tell how to force the NPM cli (via config or otherwise) to use an agent that doesn't call the `CONNECT` method on HTTP requests?

**Comment by aSapien** [comment]
Or maybe other participants here know? @lukekarrys @wraithgar
